# Generated by Django 2.0.3 on 2018-06-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data1',
            table='data1',
        ),
    ]
